=== kontext-e/dhcp4java/xml/config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by FT (FT) -->
<!--W3C Schema generated by XMLSpy v2005 rel. 3 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jxb="http://java.sun.com/xml/ns/jaxb" elementFormDefault="qualified" jxb:version="2.0">
	<!--=== Definition of simple types ===-->
	<xs:complexType name="empty-type">
		<xs:annotation>
			<xs:documentation>Used for empty elements</xs:documentation>
		</xs:annotation>
	</xs:complexType>
	<xs:simpleType name="wByte">
		<xs:annotation>
			<xs:appinfo>
				<jxb:javaType name="byte" parseMethod="javax.xml.bind.DatatypeConverter.parseByte" printMethod="javax.xml.bind.DatatypeConverter.printByte"/>
			</xs:appinfo>
			<xs:documentation>wide Byte: unsigned and signed allowed</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:short">
			<xs:minInclusive value="-128"/>
			<xs:maxInclusive value="255"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="wShort">
		<xs:annotation>
			<xs:appinfo>
				<jxb:javaType name="short" parseMethod="javax.xml.bind.DatatypeConverter.parseShort" printMethod="javax.xml.bind.DatatypeConverter.printShort"/>
			</xs:appinfo>
			<xs:documentation>wide Short:  unsigned and signed allowed</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:minInclusive value="-32768"/>
			<xs:maxInclusive value="65535"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="inet-address">
		<xs:annotation>
			<xs:appinfo>
				<jxb:javaType name="java.net.InetAddress" parseMethod="org.dhcpcluster.config.xml.Util.parseInetAddress" printMethod="org.dhcpcluster.config.xml.Util.printInetAddress"/>
			</xs:appinfo>
			<xs:documentation>InetAddress Java mapping</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="stype-option-mode">
		<xs:annotation>
			<xs:appinfo>
				<jxb:typesafeEnumClass name="OptionMode"/>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="replace"/>
			<xs:enumeration value="concat"/>
			<xs:enumeration value="regex"/>
		</xs:restriction>
	</xs:simpleType>
	<!--=== Root element ===-->
	<xs:element name="dhcp-server">
		<xs:complexType>
			<xs:all>
				<xs:element name="front-end">
					<xs:complexType>
						<xs:all>
							<xs:element name="listen" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="port" type="xs:unsignedShort" use="optional" default="67"/>
									<xs:attribute name="inet" type="inet-address" use="optional" default="127.0.0.1"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="threads" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="nb" use="optional" default="2">
										<xs:simpleType>
											<xs:restriction base="xs:int">
												<xs:minInclusive value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="max" use="optional" default="10">
										<xs:simpleType>
											<xs:restriction base="xs:int">
												<xs:minInclusive value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="core" use="optional" default="2">
										<xs:simpleType>
											<xs:restriction base="xs:int">
												<xs:minInclusive value="1"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="keepalive" use="optional" default="10000">
										<xs:simpleType>
											<xs:restriction base="xs:int">
												<xs:minInclusive value="0"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="global">
					<xs:complexType>
						<xs:all>
							<xs:element name="server" minOccurs="0">
								<xs:complexType>
									<xs:attribute name="identifier" type="inet-address" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:all>
					</xs:complexType>
				</xs:element>
				<xs:element name="topology">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="options"/>
							<xs:element ref="filter"/>
							<xs:element name="subnet">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="giaddr" maxOccurs="unbounded"/>
										<xs:element name="range">
											<xs:complexType>
												<xs:attribute name="start" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="192.168.0.15"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
												<xs:attribute name="end" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="192.168.0.25"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element ref="options"/>
										<xs:element ref="static" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="address" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="192.168.0.0"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="mask" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="255.255.252.0"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="comment" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="Free comment!"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="giaddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="10.11.12.13"/>
				<xs:enumeration value="10.11.13.15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="option">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="option-generic">
					<xs:attribute name="code" type="wByte" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="options">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="option"/>
				<xs:group ref="group-option-inets"/>
				<xs:group ref="group-option-inet"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="static">
		<xs:complexType>
			<xs:attribute name="address" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="192.168.0.3"/>
						<xs:enumeration value="192.168.0.4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="ethernet" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="0:1c0:c3:49:2b:57"/>
						<xs:enumeration value="0:c0:c3:49:2b:57"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<!--=== option value elements ===-->
	<xs:element name="mirror" type="empty-type">
		<xs:annotation>
			<xs:documentation>mirror flag, empty element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="value-byte" type="wByte"/>
	<xs:element name="value-short" type="wShort"/>
	<xs:element name="value-int" type="xs:int"/>
	<xs:element name="value-inet" type="inet-address"/>
	<xs:element name="value-rawhex" type="xs:hexBinary"/>
	<xs:element name="value-raw64" type="xs:base64Binary"/>
	<!--=== option container ===-->
	<xs:complexType name="option-generic">
		<xs:choice>
			<xs:element ref="mirror"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="value-byte"/>
				<xs:element ref="value-short"/>
				<xs:element ref="value-int"/>
				<xs:element ref="value-inet"/>
				<xs:element ref="value-rawhex"/>
				<xs:element ref="value-raw64"/>
			</xs:choice>
		</xs:choice>
		<xs:attribute name="mode" type="stype-option-mode" default="replace"/>
	</xs:complexType>
	<xs:group name="group-option-inets">
		<xs:choice>
			<xs:element name="option-time-servers" type="type-option-inets" minOccurs="0"/>
			<xs:element name="option-routers" type="type-option-inets" minOccurs="0"/>
		</xs:choice>
	</xs:group>
	<xs:group name="group-option-inet">
		<xs:choice>
			<xs:element name="option-host-name" type="type-option-inet" minOccurs="0"/>
		</xs:choice>
	</xs:group>
	<!--=== option containers by allowed types ===-->
	<xs:complexType name="type-option-inets">
		<xs:complexContent>
			<xs:restriction base="option-generic">
				<xs:choice>
					<xs:element ref="mirror"/>
					<xs:choice minOccurs="0" maxOccurs="unbounded">
						<xs:element ref="value-inet"/>
					</xs:choice>
				</xs:choice>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="type-option-inet">
		<xs:complexContent>
			<xs:restriction base="option-generic">
				<xs:choice>
					<xs:element ref="mirror"/>
					<xs:choice>
						<xs:element ref="value-inet"/>
					</xs:choice>
				</xs:choice>
			</xs:restriction>
		</xs:complexContent>
	</xs:complexType>
	<!--=== filters ===-->
	<xs:simpleType name="stype-filter-num">
		<xs:restriction base="xs:string">
			<xs:enumeration value="eq"/>
			<xs:enumeration value="ne"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="gt"/>
			<xs:enumeration value="le"/>
			<xs:enumeration value="ge"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="type-filter-root"/>
	<xs:group name="filter-group">
		<xs:choice>
			<xs:element name="filter-and">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="type-filter-root">
							<xs:group ref="filter-group" minOccurs="0" maxOccurs="unbounded"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="filter-or">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="type-filter-root">
							<xs:group ref="filter-group" minOccurs="0" maxOccurs="unbounded"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="filter-not">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="type-filter-root">
							<xs:group ref="filter-group"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="filter-always-true" type="type-filter-root"/>
			<xs:element name="filter-always-false" type="type-filter-root"/>
			<xs:element name="filter-num-option">
				<xs:complexType>
					<xs:attribute name="op" type="stype-filter-num" use="required"/>
					<xs:attribute name="code" type="wByte" use="required"/>
					<xs:attribute name="value-int" type="xs:int" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:group>
	<xs:element name="filter">
		<xs:complexType>
			<xs:group ref="filter-group"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kontext-e/dhcp4java/config/configtest.xml
<!--This is a test configuration, used by unit tests-->
<dhcp-server xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="E:\workspace\dhcp4java\xml\config.xsd">
	<front-end>
		<listen port="6767" inet="127.0.0.1"/>
		<threads nb="2" max="10" core="2" keepalive="10000"/>
	</front-end>
	<global>
		<server identifier="192.168.1.1"/>
	</global>
	<topology>
		<options>
			<option-routers>
				<value-inet>204.254.239.1</value-inet>
			</option-routers>
			<option code="129">
				<value-byte>255</value-byte>
				<value-rawhex>0022FF</value-rawhex>
			</option>
		</options>
		<subnet address="192.168.0.0" mask="255.255.252.0" comment="Free comment!">
			<giaddr>10.11.12.13</giaddr>
			<giaddr>10.11.13.15</giaddr>
			<range start="192.168.0.15" end="192.168.0.25"/>
			<options>
				<option code="15">
					<value-byte>127</value-byte>
					<value-inet>192.168.0.11</value-inet>
				</option>
				<option code="160">
					<value-short>1500</value-short>
				</option>
				<option-time-servers>
					<value-inet>192.168.0.10</value-inet>
				</option-time-servers>
				<option code="1">
					<value-byte>255</value-byte>
				</option>
				<option-host-name>
					<mirror/>
				</option-host-name>
				<!--TODO add BOOTP parameters-->
				<!--TODO add lease and max-lease-->
<!--				<lease defalut="86400" max="86400"/>-->
			</options>
			<static address="192.168.0.3" ethernet="0:c0:c3:49:2b:57"/>
			<static address="192.168.0.4" ethernet="0:1c0:c3:49:2b:57"/>
			<!--TODO add static addresses-->
			<!--TODO add allow/deny policies-->
		</subnet>
	</topology>
</dhcp-server>
